name: Bug report
description: Found a bug? Please tell us, please.
labels:
  - 'bug'
assignees: ''
body:
    - type: textarea
      id: describe
      attributes:
        label: Describe the bug
        description: A clear and concise description of what the bug is.
      validations:
        required: true
    
    - type: textarea
      id: reproduce
      attributes:
        label: To Reproduce
        description: Steps to reproduce the behaviour:
      validations:
        required: true
    
    - type: textarea
      id: behaviour
      attributes:
        label: Expected behaviour
        description: A clear and concise description of what should've happened (instead of your bug).
      validations:
        required: false
    
    - type: textarea
      id: screenshots
      attributes:
        label: Screenshots
        description: If applicable, add screenshots to help explain your problem.
      validations:
        required: false

    - type: textarea
      id: version
      attributes:
        label: Script version
      validations:
        required: true

    - type: textarea
      id: context
      attributes:
        label: Additional context
        description: Add any other context about the problem here.
      validations:
        required: false