name: Enquiry
description: Want to ask a question?
labels:
  - 'bug'
assignees: ''
body:
    - type: textarea
      id: question
      attributes:
        label: What's your question?
      validations:
        required: true