name: "Enquiry"
description: "Want to ask a question?"
labels:
  - 'question'
body:
    - type: textarea
      id: question
      attributes:
        label: "What's your question?"
      validations:
        required: true
